### ISSUE TITLE
Name of LoadedConfig

### ISSUE THREAD

**Issue by slemrmartin** [RedHatInsights/clowder-common-ruby#8]
I want to discuss the name of `LoadedConfig`, it seems it's the only class used outside of a gem.
I would like to have some namespace. Can we use `AppCommonRuby::Config`?
@mkanoor @hsong-rh

**Comment by hsong-rh** [comment]
@slemrmartin I am ok with `AppCommonRuby::Config`, how about you? @mkanoor

**Comment by mkanoor** [comment]
👍 Looks good

**Comment by slemrmartin** [comment]
I just received new Clowder doc https://clowder-operator.readthedocs.io/en/latest/providers/kafka.html
In the chapter Client access there is the same class for all languages so we probably shouldn't do it

**Comment by slemrmartin** [comment]
@psav what do you think about that? Can we make it different and can you update the doc? 
It's hard to say with what will `LoadedConfig` collide so it's not a good practise to make classes in gems without namespace
